### ISSUE TITLE
<AP> RC500S Power Resume Issue

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Product-Hardware-Issue#2]
See if new firmware can get it solved. Ready in June?
Situation: RC500S shuts down when going from ACC to engine on and it does not restart afterwards while BlackVue manages to do so.

**Comment by dod-pm1** [comment]
Tested with 2 different version of firmware, 1705251 & 1705250 both works fine.
This will be taking care of with the new firmware release in June.

**Comment by dod-pm1** [comment]
Update:

1705251 & 1705250 differ from "idle time to shut down".
New FW will be using the 5sec setting.
Which means the power can be off and resume within 5 sec. 
This should be enough for cranking the engine.
