### ISSUE TITLE
<AP> RC500S file-sorted issue

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Product-Hardware-Issue#3]
AU RC500S user 
"I notice that when I first turn on the car in the morning when I'm in the garage the first few files don't have the time and date recorded in the file name so they don't get sorted properly and are hard to find. Might have to do with it taking time to find a GPS signal but I tell it to configure time and date manually so it should already know what time and date it is. Also, sometimes the first few minutes are not recorded at all. Any ideas on what might be happening there?"

**Comment by dod-pm1** [comment]
Same issue as the cases in Taiwan, due to battery/ capacitor issue.
This is a "mechanical" problem which can be semi-fixed by firmware.
Its' being solved by chipset manufacturer right now.
Stay put for now...sorry about that.

**Comment by DOD-AP-Sales** [comment]
New FW got it solved.
