### ISSUE TITLE
<AP> LS500W Flickering Video

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Product-Hardware-Issue#7]
Model: LS500W
FW: prj_LS500W_1706131fw_A0P
SN: 88W4H01308AO
Issue: Flickering video
Frequency: 50Hz
Area: AU
Video: provided on Skype on Aug 10th, 2017.

**Comment by dod-pm1** [comment]
Saw the video, its the indoor lighting frequency.....please move it outside to eliminate this.
This ain't an actual issue, thanks~
