### ISSUE TITLE
<AP> RC500S front cam: Out of focus

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Product-Hardware-Issue#8]
Model: RC500S
FW: prj_RC500S_1707030fw_A0P_encrypt
SN: Unknown
Issue: Front cam is out of focus....
Area: AU
![rc500s front cam out of focus](https://user-images.githubusercontent.com/29158647/29160631-960b92d4-7de5-11e7-87cf-58654aa0bc15.png)

**Comment by dod-pm1** [comment]
Hi, solution coming up, possibily changing lens.
samples will be provided this week and videos as well.

**Comment by DOD-AP-Sales** [comment]
DOA
